// Code generated by ogen, DO NOT EDIT.

package api

import (
	decimal3 "github.com/adrianlungu/ogen/_testdata/testtypes/bar/decimal"
	decimal2 "github.com/adrianlungu/ogen/_testdata/testtypes/foo/decimal"
	"github.com/adrianlungu/ogen/json"
	"github.com/go-faster/jx"
)

// setDefaults set default value of fields.
func (s *OptionalOK) setDefaults() {
	{
		val, _ := json.DecodeExternal[decimal2.Decimal](jx.DecodeStr("\"1.23\""))
		s.Foo.SetTo(val)
	}
	{
		val, _ := json.DecodeExternal[decimal3.Decimal](jx.DecodeStr("1.23"))
		s.Bar.SetTo(val)
	}
}
