// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/adrianlungu/ogen/conv"
	"github.com/adrianlungu/ogen/middleware"
	"github.com/adrianlungu/ogen/ogenerrors"
	"github.com/adrianlungu/ogen/uri"
	"github.com/adrianlungu/ogen/validate"
	"github.com/go-faster/errors"
)

// UpdateWorkflowMappingParams is parameters of updateWorkflowMapping operation.
type UpdateWorkflowMappingParams struct {
	ID int
}

func unpackUpdateWorkflowMappingParams(packed middleware.Parameters) (params UpdateWorkflowMappingParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeUpdateWorkflowMappingParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateWorkflowMappingParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
